version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn api_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8010:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db/malware_cache_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_ENV=1
      - REDIS_CACHE_MANAGER=1

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: malware_cache_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5020:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
  
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight   
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_volume_data:/db



volumes:
  postgres_data:
  redis_volume_data:
  redis_insight_volume_data: