name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build services
      run: |
        # Build all services defined in docker-compose
        docker-compose -f docker-compose.yml build

    - name: Run tests with test_runner
      run: |
        # Run only the test_runner service using the test profile
        docker-compose -f docker-compose.yml --profile test up --abort-on-container-exit test_runner

        # Check exit codes of all containers
        docker-compose -f docker-compose.yml ps
      continue-on-error: true  # Continue workflow even if tests fail to allow result reporting

    - name: Publish test results
      uses: actions/upload-test-report@v1
      with:
        report_files: test-reports/results.xml

    - name: Clean up
      if: always()
      run: docker-compose -f docker-compose.yml down
