name: Build and tests 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build services
      run: |
        # Build all services defined in docker-compose
        docker-compose -f docker-compose.yml build

    - name: Run tests with test_runner
      run: |
        # Create a directory for test reports
        mkdir -p test-reports
        
        # Run the test_runner service using the test profile
        docker-compose -f docker-compose.yml --profile test up --abort-on-container-exit test_runner
        
        # Move the test report if generated
        docker cp test_runner:/app/test-reports/results.xml ./test-reports/results.xml || true
      continue-on-error: true  # Continue workflow even if tests fail to upload results

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-reports/results.xml

    - name: Clean up
      if: always()
      run: docker-compose -f docker-compose.yml down
